In [1]:
import pandas as pd
df = pd.read_csv("comments.csv")

## Play with data

In [2]:

raw_numbers = list(df["phone_number"])
numbers = set(raw_numbers)
print("There are " + str(len(numbers)) + " phone numbers.")
print("There are " + str(len(raw_numbers)) + " comments in total.")

There are 39645 phone numbers.
There are 246534 comments in total.

In [3]:
valid_comments = df[df.call_type.notnull()]
print("There are " + str(len(valid_comments)) + " comments can be used.")

There are 70607 comments can be used.

In [5]:
number_df = df.groupby("phone_number").count()
useful_number_df = number_df[number_df["content"] >= 1]
useful_number_df = number_df[number_df["call_type"] >= 1]
useful_number_df.sort_values("content", ascending=False)

                content  datetime  caller  call_type
phone_number
1-253-802-0308     1053      1053     467        124
1-206-456-0661      826       826     342         89
1-212-920-8181      594       594      94         44
1-925-524-3099      496       496     198        134
1-360-529-6177      445       445     183        149
1-319-242-7350      422       422     221        116
1-757-961-3544      409       409     157        132
1-954-905-4135      390       390      71         33
1-347-218-0531      374       374     156        101
1-800-764-0847      369       369      46          1
1-360-529-6156      360       360     134        101
1-855-876-5380      339       339     154         94
1-855-212-3031      332       332      99         75
1-818-756-7488      321       321     199        121
1-603-856-0338      271       271     173        100
1-302-268-6660      267       267      80         31
1-307-274-3886      262       262      84         40
1-360-529-6981      260       260     119         93
1-818-870-8100      256       256     137        109
1-515-364-6750      255       255      29         16
1-202-644-8225      252       252      85         41
1-502-873-0294      249       249      69         28
1-502-632-4428      246       246      85         43
1-866-691-3568      245       245     127         93
1-360-529-6100      245       245      88         54
1-888-310-9738      240       240      84         57
1-307-215-1002      238       238      75         45
1-307-215-1001      236       236      71         56
1-360-529-6963      236       236      94         65
1-200-200-0000      232       232      87         31
...                 ...       ...     ...        ...
1-801-657-2497        1         1       1          1
1-206-331-4333        1         1       0          1
1-866-763-5083        1         1       1          1
1-801-657-3261        1         1       1          1
1-801-657-3320        1         1       0          1
1-866-740-6931        1         1       1          1
1-866-740-4846        1         1       1          1
1-801-657-4614        1         1       1          1
1-801-657-4905        1         1       0          1
1-801-657-5042        1         1       1          1
1-240-780-0989        1         1       1          1
1-206-237-6308        1         1       0          1
1-206-237-5382        1         1       1          1
1-801-618-2055        1         1       1          1
1-206-237-0047        1         1       1          1
1-866-763-3396        1         1       1          1
1-206-237-0844        1         1       1          1
1-801-447-4166        1         1       0          1
1-801-447-5286        1         1       1          1
1-801-544-0000        1         1       1          1
1-801-568-2810        1         1       1          1
1-240-786-8637        1         1       1          1
1-801-618-1297        1         1       1          1
1-240-786-5469        1         1       0          1
1-206-237-1523        1         1       1          1
1-206-237-2963        1         1       0          1
1-866-761-3964        1         1       1          1
1-866-761-3867        1         1       1          1
1-240-786-4640        1         1       1          1
1-319-249-0500        1         1       0          1

[19321 rows x 4 columns]

In [11]:
call_type_df = df.groupby("call_type").count()
call_type_df.sort_values("content", ascending=False)

                         content  phone_number  datetime  caller
call_type
Telemarketer               22470         22470     22470   15328
Debt collector             20775         20775     20775   16745
Scam suspicion             14905         14905     14905   10084
Prank                       2513          2513      2513    1766
Unwanted                    2307          2307      2307    1546
Survey                      1746          1746      1746    1176
Political call              1420          1420      1420     931
Text message                1146          1146      1146     648
Non-profit organization     1134          1134      1134     903
Event reminder               728           728       728     631
Valid                        521           521       521     422
Fax                          519           519       519     325
Silent call                  423           423       423     197

In [12]:
import os

base_path = 'C:\\Users\\wang_cheng\\git_stuff\\crawler\\800notes\\original\\Spider\\800notes\\'
base_url = "https://800notes.com/Phone.aspx/"

json_number_lis = []

for path, subdirs, files in os.walk(base_path):
    if(not subdirs):
        continue
    for filename in files:
        json_number_lis.append(filename.split(".json")[0])

In [13]:
not_included = list(number for number in json_number_lis if number not in numbers)
print(len(not_included) + len(numbers))

40112

In [17]:
df[-df.content.notnull()]

       content    phone_number     datetime         caller call_type
4652       NaN  1-202-436-9959  25 Nov 2015            NaN       NaN
9693       NaN  1-202-697-9373  16 Feb 2017            NaN       NaN
9694       NaN  1-202-697-9373  16 Feb 2017            NaN       NaN
59361      NaN  1-317-356-2341  27 Dec 2016  Robert Draper       NaN
63603      NaN  1-347-394-2384  12 Mar 2018            NaN       NaN
142972     NaN  1-818-870-8187  14 Feb 2008             na       NaN
172340     NaN  1-855-761-2771  23 Sep 2015            NaN       NaN
205085     NaN  1-866-999-6460   3 May 2016            NaN       NaN
237484     NaN  1-909-999-2928  15 Sep 2010            NaN       NaN